const test=require('node:test');const assert=require('node:assert/strict');const {setup,flush,complete}=require('./harness.cjs');
const K='sharp-final-continuous-v1',Q='sharp-final-quality-v1',B='sharp-final-backup-v2';
function legacy(){return {stats:{streak:9,sessions:20,minutes:150,last:'2026-09-11'},domains:{arithmetic:{level:4,score:63,baseline:50,best:70,attempts:50,last:'2026-09-11T12:00:00.000Z',recent:[{acc:1,ms:1500,level:4,score:60}]}},history:[{date:'2026-09-11T12:00:00.000Z',mode:'quick',score:63,minutes:8,results:[{id:'arithmetic',acc:.8,ms:1500,score:63,level:4}]}]};}
test('migration preserves old scores, history, streak and minutes; current scoring creates a separate series',async()=>{
  const original=JSON.stringify(legacy()),storage=new Map([[K,original]]),h=setup({storage});assert.equal(h.run('S.stats.streak'),9);assert.equal(h.run('S.stats.legacyMinutes'),150);assert.equal(h.run('S.stats.activeMinutes'),0);assert.equal(JSON.parse(storage.get(B)).core,original);
  h.run("start('quick');active.ids=['arithmetic'];begin()");complete(h);await flush(h);
  assert.equal(h.run('S.domains.arithmetic.legacy.score'),63);assert.equal(h.run('S.domains.arithmetic.legacy.attempts'),50);assert.equal(h.run('S.history[0].score'),63);assert.equal(h.run('S.history[0].scoringVersion'),1);assert.equal(h.run('S.stats.streak'),10);assert.equal(h.run('S.stats.sessions'),21);
  const reload=setup({storage});assert.equal(reload.run('S.domains.arithmetic.legacy.score'),63);assert.equal(reload.run('S.stats.streak'),10);assert.equal(reload.run('S.history.length'),2);assert.equal(reload.run('S.checkpoint'),null);
});
test('malformed fields are quarantined, safely repaired and cannot crash Performance',async()=>{
  const raw=JSON.stringify({stats:{sessions:'bad'},domains:{arithmetic:{level:999,score:-5}},history:[{}]}),storage=new Map([[K,raw]]),h=setup({storage});assert.equal(h.run('S.domains.arithmetic.level'),2);assert.equal(h.run('S.history.length'),0);assert.equal(JSON.parse(storage.get(B)).core,raw);h.run("page='performance';render();saveState()");await flush(h);assert.equal(h.errors.length,0);assert.notEqual(storage.get(K),raw);
});
test('unreadable data is never overwritten when the recovery backup cannot be written',async()=>{const storage=new Map([[K,'{broken']]),h=setup({storage,failKey:B});h.run('saveState()');await flush(h);assert.equal(storage.get(K),'{broken');assert.equal(h.run('persistence.blocked'),true);assert.match(h.notice.innerHTML,/Export/);});
test('quota failure is visible and a retry saves the current state',async()=>{let fail=true;const h=setup({quota:()=>fail});h.run('S.stats.sessions=7;saveState()');await flush(h);assert.equal(h.run('persistence.dirty'),true);assert.match(h.notice.innerHTML,/Quota|Export/);fail=false;h.run('saveState()');await flush(h);assert.equal(JSON.parse(h.storage.get(K)).stats.sessions,7);assert.equal(h.run('persistence.dirty'),false);assert.equal(h.run('persistence.message'),'');});
test('canonical core and quality save atomically when the compatibility mirror fails',async()=>{const h=setup({failKey:Q});h.run('QSTATE.recall.total=3;saveState()');await flush(h);assert.equal(JSON.parse(h.storage.get(K)).quality.recall.total,3);const again=setup({storage:h.storage});assert.equal(again.run('QSTATE.recall.total'),3);assert.match(h.notice.innerHTML,/compatibility/);});
test('a stale tab cannot overwrite the newer tab, even without receiving a storage event',async()=>{const storage=new Map(),a=setup({storage}),b=setup({storage});a.run('S.stats.sessions=8;saveState()');await flush(a);b.run('S.stats.sessions=1;saveState()');await flush(b);assert.equal(JSON.parse(storage.get(K)).stats.sessions,8);assert.equal(b.run('persistence.blocked'),true);assert.match(b.notice.innerHTML,/another tab/);});
test('browsers without safe write coordination show a save warning and keep original data',async()=>{const h=setup({noLocks:true});h.run('saveState()');await flush(h);assert.equal(h.storage.has(K),false);assert.match(h.notice.innerHTML,/coordinate safe saves/);});
test('invalid imports are rejected and successful imports first back up current progress',async()=>{const h=setup();h.run('S.stats.sessions=5;saveState()');await flush(h);assert.throws(()=>h.run("parseImport(JSON.stringify({format:'sharp-progress',version:2,state:{schemaVersion:2,stats:{sessions:-1}}}))"),/invalid/);h.run('var incoming=fresh();incoming.stats.sessions=99;');await h.run('importProgress(incoming)');assert.equal(h.run('S.stats.sessions'),99);assert.equal(JSON.parse(JSON.parse(h.storage.get(B)).core).stats.sessions,5);assert.equal(JSON.parse(h.storage.get(K)).stats.sessions,99);});
test('block checkpoints resume without duplicate commits or session counts',async()=>{const h=setup();h.run("start('quick');active.ids=['arithmetic','memory'];begin()");let steps=0;while(h.run("active.phase!=='blockResult'")&&steps++<10){h.tick(1000);h.run('answer(active.q.answer)');h.tick(500);}await flush(h);assert.equal(h.run('S.checkpoint.bi'),1);const restored=setup({storage:h.storage});restored.run('resumeSession()');assert.equal(restored.run('active.id'),'memory');complete(restored);await flush(restored);assert.equal(restored.run('S.stats.sessions'),1);assert.equal(restored.run('S.history[0].results.length'),2);assert.equal(restored.run('S.domains.arithmetic.attempts'),1);restored.run('finishSession();leaveSession()');await flush(restored);assert.equal(restored.run('S.stats.sessions'),1);assert.equal(restored.run('S.checkpoint'),null);});
test('new recall sets are unique, remain pending until confirmation, and failed answers stay scheduled',async()=>{const h=setup();for(let i=0;i<500;i++){h.run('QSTATE=qualityFresh();prepareEncoding()');assert.equal(h.run('new Set(QSTATE.recall.pending.map(i=>i.word)).size'),5);assert.equal(h.run('QSTATE.recall.items.length'),0);}h.run('commitEncoding()');assert.equal(h.run('QSTATE.recall.items.length'),5);h.run("var item=QSTATE.recall.items[0];recordRecall(item,'00');recordRecall(item,'00')");assert.equal(h.run('item.stage'),0);assert.equal(h.run('item.done'),false);h.run('recordRecall(item,String(item.code))');assert.equal(h.run('item.stage'),1);h.run("recordRecall(item,'00')");assert.equal(h.run('item.done'),false);h.run('recordRecall(item,String(item.code))');assert.equal(h.run('item.done'),true);await flush(h);});
test('pending encoding survives reload and is committed only after confirmation',async()=>{const h=setup();h.run("start('standard')");const words=h.read('QSTATE.recall.pending.map(i=>i.word)');await flush(h);const r=setup({storage:h.storage});r.run('resumeSession()');assert.equal(r.run('active.phase'),'qualityEncoding');assert.deepEqual(r.read('QSTATE.recall.pending.map(i=>i.word)'),words);assert.equal(r.run('QSTATE.recall.items.length'),0);r.run('finishEncoding();finishEncoding()');assert.equal(r.run('QSTATE.recall.items.length'),5);});
test('score floors and adaptation exclude incorrect speed rewards and old-level evidence',()=>{const h=setup();for(const id of ['arithmetic','words','dual','reflex'])assert.equal(h.run(`score(0,200,10,'${id}')`),0);assert.equal(h.run("stableAdapt('arithmetic',{level:5,recent:[{acc:1,ms:200,level:4,scoringVersion:2},{acc:1,ms:200,level:4,scoringVersion:2}]},{acc:1,ms:200,level:5,scoringVersion:2})"),5);assert.equal(h.run("stableAdapt('reflex',{level:2,recent:[]},{acc:.1,ms:200,level:2,scoringVersion:2})"),2);assert.ok(h.run("score(.1,200,2,'reflex')")<15);h.run('IDS.slice(0,8).forEach(id=>Object.assign(S.domains[id],{attempts:1,scoringVersion:2,score:0,baseline:100,level:1,baselineLevel:2}))');assert.equal(h.run('index().v'),0);});
test('Fisher–Yates and weighted selection are seeded, unique and include all domains over time',()=>{const h=setup();const a=h.read('seedRng(123);sh(IDS)'),b=h.read('seedRng(123);sh(IDS)');assert.deepEqual(a,b);const picked=new Set();for(let i=0;i<100;i++){const ids=h.read('weightedIds(6)');assert.equal(new Set(ids).size,6);ids.forEach(id=>picked.add(id));}assert.equal(picked.size,18);});
test('local calendar helpers handle positive/negative timezones and DST',()=>{const prior=process.env.TZ;try{for(const zone of ['Pacific/Auckland','America/New_York','Europe/London','Pacific/Honolulu']){process.env.TZ=zone;const h=setup();assert.equal(h.run("dayKey(new Date('2026-03-08T00:15:00'))"),'2026-03-08');assert.equal(h.run("addDays('2026-03-07',1)"),'2026-03-08');assert.equal(h.run("addDays('2026-11-01',1)"),'2026-11-02');assert.equal(h.run("dayDistance('2026-03-09','2026-03-08')"),1);}}finally{if(prior==null)delete process.env.TZ;else process.env.TZ=prior;}});
