const test=require('node:test');const assert=require('node:assert/strict');
const {setup,flush,complete,answerCurrent}=require('./harness.cjs');
test('selection on Text, Document and Window cannot crash or suppress unrelated selection',()=>{const h=setup();for(const target of [{nodeType:3,parentElement:{closest:()=>null}},{nodeType:9},h.context])h.dispatch('selectstart',target);assert.equal(h.errors.length,0);assert.match(h.root.innerHTML,/Make time/);assert.equal(h.run("closestElement({nodeType:3,parentElement:{closest:()=>42}},'x')"),42);});
test('answer/timeout/double answer settles once; stale callbacks cannot affect a new same-domain session',()=>{const h=setup();h.run("start('practice','arithmetic')");h.tick(500);h.run('answer(active.q.answer);timeoutQuestion();answer(active.q.answer)');assert.equal(h.run('active.qi'),1);h.run("leaveSession();start('practice','arithmetic')");h.tick(500);assert.equal(h.run('active.qi'),0);assert.equal(h.run('active.phase'),'question');assert.equal(h.run('jobs.size'),2);});
test('late response loses to deadline even when timeout task has not run',()=>{const h=setup();h.run("start('practice','arithmetic')");h.tick(100);h.run('active.deadline=mono()-1;answer(active.q.answer)');assert.equal(h.run('active.trials[0].status'),'timeout');assert.equal(h.run('active.good'),0);});
test('cancelling recall invalidates its delayed transition',async()=>{const h=setup();h.run("QSTATE.recall.items=[{id:'r',word:'orbit',code:12,stage:0,created:dayKey(),due:dayKey(),done:false}];start('standard');submitRecall('12');leaveSession();start('practice','arithmetic')");h.tick(500);assert.equal(h.run('active.id'),'arithmetic');assert.equal(h.run('active.qi'),0);assert.equal(h.errors.length,0);await flush(h);});
test('memory and visual memory enforce recall deadlines',()=>{for(const id of ['memory','visualmem']){const h=setup();h.run(`start('practice','${id}')`);h.tick(3000);assert.equal(h.run('active.phase'),'question');assert.ok(h.run('active.deadline>mono()'));h.tick(14000);assert.ok(h.run('active.qi>=1'));assert.equal(h.run('active.trials[0].status'),'timeout');}});
test('stale Dual transition cannot start a hidden timer in new encoding',()=>{const h=setup();h.run("start('practice','dual')");h.tick(3000);h.run('dualAnswer(active.q.answer)');h.run("leaveSession();start('practice','dual')");h.tick(500);assert.equal(h.run('active.phase'),'dualEncoding');assert.equal(h.run('active.deadline'),null);assert.equal([...h.timers.values()].filter(t=>t.interval).length,0);});
test('confidence locks once and excludes deliberation from response timing',()=>{const h=setup();h.run("start('practice','logic');active.practice=false");answerCurrent(h);h.tick(500);h.run('answer(active.q.answer)');assert.equal(h.run('active.phase'),'confidence');const ms=h.run('active.pendingConfidence.ms');h.tick(60000);h.run('commitConfidence(80);commitConfidence(100)');assert.equal(h.run('QSTATE.calibration.length'),1);assert.equal(h.run('active.trials[1].ms'),ms);h.tick(500);assert.equal(h.run('active.qi'),2);});
test('Stroop records all eight trials, including omissions, without fabricated interference',()=>{const h=setup();h.run("start('practice','attention')");h.tick(35000);assert.equal(h.run('active.phase'),'blockResult');const s=h.read('active.results[0].extra.stroop');assert.equal(s.congruent,2);assert.equal(s.incongruent,6);assert.equal(s.congErr,1);assert.equal(s.incongErr,1);assert.equal(s.interference,null);assert.equal(h.run('active.results[0].score'),0);});
test('Reflex cancellation is unscored, capture survives the hold, cooldown prevents a rapid new hold, and five trials finish',()=>{
  const h=setup();h.run("start('practice','reflex');reflexBegin('pointer',1,document.querySelector('[data-reflex-hold]'))");const mounted=h.root.innerHTML;h.tick(2450);assert.equal(h.root.innerHTML,mounted);h.dispatch('pointercancel',{}, {pointerId:1});assert.equal(h.run('active.reflexTimes.length'),0);assert.equal(h.run('active.reflexFalse'),0);h.tick(500);
  for(let i=0;i<5;i++){h.run("reflexBegin('pointer',1,document.querySelector('[data-reflex-hold]'))");h.tick(2450);h.run("reflexEnd('pointer',1)");if(i<4){h.run("reflexBegin('pointer',2,document.querySelector('[data-reflex-hold]'))");assert.equal(h.run('active.phase'),'reflexCooldown');h.tick(500);}}
  assert.equal(h.run('active.phase'),'blockResult');assert.equal(h.run('active.results[0].extra.valid'),5);assert.equal(h.run('jobs.size'),0);
});
test('background pause invalidates timers, excludes background minutes and safely restarts the block',()=>{const h=setup();h.run("start('practice','memory')");h.tick(500);h.run("interruptCurrent('background')");const before=h.run('engagedMs()');h.tick(600000);assert.equal(h.run('engagedMs()'),before);assert.equal(h.run('jobs.size'),0);h.run('continueSession()');assert.equal(h.run('active.phase'),'encoding');assert.equal(h.run('active.qi'),0);});
test('wall-clock jumps cannot change answer time',()=>{const h=setup();h.run("start('practice','arithmetic')");h.tick(500);h.jumpWall(3600000);h.run('answer(active.q.answer)');assert.ok(h.run('active.trials[0].ms')<1000);});
test('runtime recovery keeps navigation and invalidates the interrupted phase',()=>{const h=setup();h.run("start('practice','dual')");h.tick(500);h.run("handleRuntimeError(new Error('fixture'))");assert.equal(h.run('active.phase'),'error');assert.match(h.root.innerHTML,/Restart current block/);h.tick(10000);assert.equal(h.run('active.phase'),'error');h.run('continueSession()');assert.equal(h.run('active.phase'),'dualEncoding');});
test('all 18 practices, complete Full Daily, Quick and Focused Daily reach completion without duplicate results',async()=>{
  for(const id of ['arithmetic','estimation','logic','patterns','matrix','spatial','planning','attention','sustained','processing','flexibility','memory','visualmem','dual','words','verbal','strategy','reflex']){const h=setup();h.run(`start('practice','${id}')`);complete(h);assert.equal(h.run('active.phase'),'blockResult',id);assert.equal(h.run('S.stats.sessions'),0);assert.equal(h.run(`S.domains.${id}.attempts`),0);}
  for(const mode of ['standard','quick','focused']){const h=setup();h.run(`start('${mode}')`);complete(h);await flush(h);assert.equal(h.run('active.phase'),'sessionResult',mode);assert.equal(h.run('S.stats.sessions'),1);assert.equal(h.run('new Set(active.h.results.map(r=>r.blockId)).size'),h.run('active.h.results.length'));if(mode==='standard')assert.equal(h.run('active.h.results.length'),19);if(mode==='quick')assert.equal(h.run('active.h.results.length'),6);if(mode==='focused')assert.ok(h.run('active.h.minutes')>=10);assert.equal(h.errors.length,0);assert.equal(h.run('persistence.dirty'),false);}
});
test('pausing a held Reflex touch releases capture without leaving the paused state',()=>{const h=setup();h.run("start('practice','reflex');reflexBegin('pointer',1,document.querySelector('[data-reflex-hold]'))");h.tick(500);h.run("interruptCurrent('background')");h.dispatch('lostpointercapture',{}, {pointerId:1});h.tick(10000);assert.equal(h.run('active.phase'),'paused');assert.equal(h.run('active.reflexInput'),null);assert.equal(h.run('active.reflexFalse'),0);});
