'use strict';
const root=document.getElementById('root');let page='today',active=null,timerHandle=null,memoryHandle=null;
function clearTimers(){clearInterval(timerHandle);clearTimeout(memoryHandle);clearTimeout(active?.reflexWait);timerHandle=memoryHandle=null}
function nav(){return`<nav class="nav">${[['today','⌂','Today'],['train','▶','Train'],['performance','⌁','Performance'],['games','◇','Games']].map(x=>`<button data-nav="${x[0]}" class="${page===x[0]?'on':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
function shell(x){return`<div class="app"><div class="top"><div class="logo">SHARP</div><div class="dot"></div></div>${x}</div>${nav()}`}
function index(){let trained=IDS.filter(id=>S.domains[id].attempts),v=trained.length>=8?Math.round(trained.reduce((a,id)=>a+S.domains[id].score,0)/trained.length-(IDS.length-trained.length)*.8):null;return{v,trained}}
function focus(){return [...IDS].sort((a,b)=>(S.domains[a].score+days(S.domains[a].last)*-2)-(S.domains[b].score+days(S.domains[b].last)*-2))[0]}
function drow(id){let d=S.domains[id];return`<div class="drow"><div class="dtop"><span>${META[id][0]}</span><b>${d.attempts?d.score:'BASELINE'}</b></div><div class="bar"><i style="width:${d.attempts?d.score:0}%"></i></div></div>`}
function game(id){let d=S.domains[id];return`<div class="game" data-practice="${id}"><div class="ico">${META[id][1]}</div><div><h3>${META[id][0]}</h3><p>${META[id][2]}</p></div><div class="lvl"><small>LEVEL</small><strong>${d.level}</strong></div></div>`}
function today(){let f=focus(),ix=index();root.innerHTML=shell(`<section class="hero"><div class="eye">Daily cognitive training</div><h1>Train the full<br>system.</h1><p>Sixteen measured cognitive systems. Full Daily tests every one; difficulty adapts independently.</p></section><section class="card focus"><div class="head"><div><div class="eye">Current priority</div><h2 style="margin-top:7px">${META[f][0]}</h2></div><span class="chip">LEVEL ${S.domains[f].level}</span></div><p>${S.domains[f].attempts?'Currently one of your weakest signals.':'Baseline data needed.'}</p><div class="row"><button class="btn primary" data-start="standard">Full Daily</button><button class="btn secondary" data-start="quick">Quick</button></div></section><div class="section"><h3>Current signal</h3></div><div class="grid3"><div class="metric"><small>Sharpness</small><strong>${ix.v??'—'}</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div><div class="metric"><small>Minutes</small><strong>${Math.round(S.stats.minutes)}</strong></div></div>`)}
function train(){root.innerHTML=shell(`<section class="hero"><div class="eye">Session control</div><h1>Choose the<br>workload.</h1><p>Full Daily measures all 16 systems. Quick targets six systems for days when time is limited.</p></section><div class="grid2"><section class="card"><div class="eye">Quick</div><h2 style="margin-top:7px">10–15m</h2><p>Six targeted systems.</p><button class="btn primary" data-start="quick" style="width:100%">Start</button></section><section class="card"><div class="eye">Full Daily</div><h2 style="margin-top:7px">25–35m</h2><p>All sixteen systems.</p><button class="btn primary" data-start="standard" style="width:100%">Start</button></section></div>`)}
function performancePage(){let ix=index(),rank=[...ix.trained].sort((a,b)=>S.domains[b].score-S.domains[a].score),hist=[...S.history].reverse().slice(0,6);root.innerHTML=shell(`<section class="hero"><div class="eye">Performance intelligence</div><h1>${ix.v??'—'}<span style="font-size:.32em;color:var(--mut)"> /100</span></h1><p>${ix.v==null?'Complete more domains to establish the index.':'Internal training index, not an IQ score.'}</p></section><div class="grid3"><div class="metric"><small>Sessions</small><strong>${S.stats.sessions}</strong></div><div class="metric"><small>Trained</small><strong>${ix.trained.length}/16</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div></div>${rank.length?`<div class="section"><h3>Signal</h3></div><div class="grid2"><div class="metric"><small>Strongest</small><strong style="font-size:15px">${META[rank[0]][0]}</strong></div><div class="metric"><small>Weakest</small><strong style="font-size:15px">${META[rank.at(-1)][0]}</strong></div></div>`:''}<div class="section"><h3>Domain profile</h3></div><section class="card">${IDS.map(drow).join('')}</section><div class="section"><h3>Recent sessions</h3></div>${hist.length?hist.map(h=>`<div class="game"><div class="ico">${h.score}</div><div><h3>${h.mode==='standard'?'Full Daily':'Quick'} session</h3><p>${new Date(h.date).toLocaleDateString()} · ${h.results.length} systems</p></div></div>`).join(''):'<div class="empty">No completed sessions yet.</div>'}`)}
function gamesPage(){root.innerHTML=shell(`<section class="hero"><div class="eye">Practice lab</div><h1>Train one<br>system.</h1><p>Practice does not affect your daily streak.</p></section>${IDS.map(game).join('')}`)}
function render(){if(active?.screen==='question')return question();if(active?.screen==='memory')return memoryScreen();if(active?.screen==='visualmem')return visualMemoryScreen();if(active?.screen==='words')return wordsScreen();if(active?.screen==='reflex')return reflexScreen();if(active?.screen==='blockResult')return blockResult();if(active?.screen==='sessionResult')return sessionResult();({today,train,performance:performancePage,games:gamesPage}[page]||today)()}
function quickIds(){return [...IDS].sort((a,b)=>(S.domains[a].score+Math.random()*15)-(S.domains[b].score+Math.random()*15)).slice(0,6)}
function start(mode,only){let ids=only?[only]:(mode==='standard'?[...IDS]:quickIds());active={mode,practice:!!only,ids,bi:0,results:[],start:Date.now(),screen:'question'};begin()}
function countFor(id,mode){if(id==='reflex')return 5;if(id==='words')return 1;return mode==='quick'?4:5}
function begin(){clearTimers();let id=active.ids[active.bi];Object.assign(active,{id,qi:0,count:countFor(id,active.mode),good:0,times:[],errors:[],prevRule:null,timeouts:0});if(id==='words')return startWords();if(id==='reflex')return startReflex();next()}
function next(){if(active.qi>=active.count)return finishBlock();let q=gen(active.id,S.domains[active.id].level,active.prevRule);active.q=q;if(q.kind==='memory'){active.screen='memory';active.memoryHidden=false;render();memoryHandle=setTimeout(()=>{if(active?.q===q){active.memoryHidden=true;active.qStart=Date.now();render()}},q.display);return}if(q.kind==='visualmem'){active.screen='visualmem';active.memoryHidden=false;render();memoryHandle=setTimeout(()=>{if(active?.q===q){active.memoryHidden=true;active.qStart=Date.now();render()}},q.display);return}active.screen='question';active.qStart=Date.now();active.limit=timeLimit(active.id,S.domains[active.id].level);active.deadline=Date.now()+active.limit*1000;render();timerHandle=setInterval(updateTimer,100)}
function updateTimer(){if(!active||!active.deadline)return;let rem=(active.deadline-Date.now())/1000,n=document.getElementById('timerNum'),f=document.getElementById('timerFill');if(n)n.textContent=Math.max(0,rem).toFixed(1)+'s';if(f){let p=cl(rem/active.limit*100,0,100);f.style.width=p+'%';f.classList.toggle('low',p<25)}if(rem<=0){clearInterval(timerHandle);timerHandle=null;if(active.screen==='words')finishWords();else timeoutQuestion()}}
function timeoutQuestion(){if(!active)return;active.times.push(active.limit*1000);active.errors.push('timeout');active.timeouts++;flash(false,active.q.answer);active.qi++;setTimeout(next,400)}
function headProgress(){return`<div class="shead"><button class="x" data-exit>×</button><div><div class="prog"><i style="width:${((active.bi+active.qi/Math.max(1,active.count))/active.ids.length)*100}%"></i></div><div class="prog" style="margin-top:7px"><i id="timerFill" style="width:100%"></i></div></div><div class="timer" id="timerNum">${active.limit?active.limit.toFixed(1)+'s':''}</div></div>`}
function question(){let q=active.q;root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap"><div class="eye">${META[active.id][0]} · Level ${S.domains[active.id].level} · ${active.qi+1}/${active.count}</div>${questionVisual(q)}<div class="sub">${esc(q.sub||'')}</div></div>${answerUI(q)}</main></div>`;updateTimer();if(q.kind==='number')setTimeout(()=>document.getElementById('ans')?.focus(),30)}
function gridHtml(key,n){return`<div class="miniGrid" style="grid-template-columns:repeat(${n},1fr)">${key.split('').map(x=>`<i class="${x==='1'?'on':''}"></i>`).join('')}</div>`}
function questionVisual(q){if(q.kind==='matrix')return`<div class="matrix">${q.cells.map((x,i)=>`<div class="mcell ${i===8?'miss':''}">${esc(x)}</div>`).join('')}</div>`;if(q.kind==='spatial')return`<div style="margin:18px auto">${gridHtml(q.baseKey,q.n)}<div class="eye" style="margin-top:12px">${esc(q.sub)}</div></div>`;if(q.kind==='route'){let walls=new Set(q.walls);return`<div class="routeGrid" style="grid-template-columns:repeat(${q.n},1fr)">${Array.from({length:q.n*q.n},(_,i)=>`<div class="routeCell ${i===0?'start':i===q.n*q.n-1?'goal':walls.has(i)?'wall':''}">${i===0?'S':i===q.n*q.n-1?'G':''}</div>`).join('')}</div>`}if(q.kind==='stroop')return`<div class="q" style="color:${q.ink};margin-top:18px">${esc(q.prompt)}</div>`;return`<div class="q ${String(q.prompt).length>42?'compact':''}" style="margin-top:16px">${esc(q.prompt)}</div>`}
function answerUI(q){if(q.kind==='matrix')return`<div class="matrixAnswers">${q.options.map(o=>`<button class="matrixOption" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(q.kind==='spatial'||q.kind==='visualmem')return`<div class="patternAnswers">${q.options.map(o=>`<button class="patternOption" data-answer="${o}">${gridHtml(o,q.n)}</button>`).join('')}</div>`;if(q.kind==='choice'||q.kind==='route'||q.kind==='stroop')return`<div class="options">${q.options.map(o=>`<button class="option" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;return`<form class="form" id="form"><input class="input" id="ans" inputmode="numeric" autocomplete="off" placeholder="Answer"><button class="btn primary submit" type="submit">→</button></form>`}
function answer(r){if(!active)return;clearInterval(timerHandle);let ms=Math.max(1,Date.now()-active.qStart),ok=correct(active.q,r);active.times.push(ms);if(ok)active.good++;else active.errors.push(ms<850?'impulsive':'incorrect');if(active.id==='flexibility')active.prevRule=active.q.meta?.rule||active.prevRule;flash(ok,active.q.answer);active.qi++;setTimeout(next,330)}
function flash(ok,a){let d=document.createElement('div');d.className='feedback '+(ok?'ok':'no');d.textContent=ok?'Correct':'Answer: '+a;document.body.appendChild(d);setTimeout(()=>d.remove(),550)}
function memoryScreen(){let q=active.q,hidden=active.memoryHidden;root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.qi/active.count*100}%"></i></div><div class="timer">${active.qi+1}/${active.count}</div></div><div class="qwrap"><div class="eye">Working Memory · Level ${S.domains.memory.level}</div><div class="q" style="margin-top:18px">${hidden?'Enter reverse sequence':esc(q.prompt)}</div><div class="sub">${hidden?'Reverse the order from memory.':'Memorise this sequence.'}</div></div>${hidden?answerUI({kind:'number'}):''}</main></div>`;if(hidden)setTimeout(()=>document.getElementById('ans')?.focus(),30)}
function visualMemoryScreen(){let q=active.q,hidden=active.memoryHidden;root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.qi/active.count*100}%"></i></div><div class="timer">${active.qi+1}/${active.count}</div></div><div class="qwrap"><div class="eye">Visual Memory · Level ${S.domains.visualmem.level}</div>${hidden?'<h2>Which pattern did you see?</h2>':gridHtml(q.pattern,q.n)}<div class="sub">${hidden?'Select from memory.':'Memorise the highlighted cells.'}</div></div>${hidden?answerUI(q):''}</main></div>`}
function startWords(){let bank=pk(WORD_BANK),l=S.domains.words.level,total=Math.max(40,70-l*3);Object.assign(active,{screen:'words',wordBank:bank,wordLetters:sh(bank.l.split('')),wordUsed:[],wordFound:[],wordTarget:cl(4+Math.floor(l*.7),4,10),limit:total,deadline:Date.now()+total*1000,wordLast:Date.now()});render();timerHandle=setInterval(updateTimer,100)}
function wordsScreen(){let cur=active.wordUsed.map(i=>active.wordLetters[i]).join('');root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap" style="justify-content:flex-start;padding-top:42px"><div class="eye">Word Fluency · Level ${S.domains.words.level}</div><h2 style="margin-top:8px">Anagram Sprint</h2><p>${active.wordFound.length}/${active.wordTarget} target words · 3+ letters</p><div class="wordbuild">${esc(cur)||'&nbsp;'}</div><div class="tiles">${active.wordLetters.map((c,i)=>`<button class="tile" data-letter="${i}" ${active.wordUsed.includes(i)?'disabled':''}>${c}</button>`).join('')}</div><div class="wordactions"><button class="btn secondary" data-word-back>⌫</button><button class="btn secondary" data-word-shuffle>Shuffle</button><button class="btn primary" data-word-submit>↵</button></div><div class="found">${esc(active.wordFound.join(' · '))}</div></div></main></div>`;updateTimer()}
function wordSubmit(){let w=active.wordUsed.map(i=>active.wordLetters[i]).join('').toLowerCase();active.wordUsed=[];if(w.length<3)return wordNote('3+ letters');if(active.wordFound.includes(w))return wordNote('Already found');if(active.wordBank.w.includes(w)){active.wordFound.push(w);wordNote('✓ '+w,true)}else wordNote('Not in this challenge');wordsScreen()}
function wordNote(t,ok=false){let d=document.createElement('div');d.className='feedback '+(ok?'ok':'no');d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),550)}
function finishWords(){let n=active.wordFound.length,acc=Math.min(1,n/active.wordTarget),ms=active.limit*1000/Math.max(1,n);active.good=n;active.count=active.wordTarget;active.times=[ms];finishBlock(acc,ms,{found:n})}
function startReflex(){Object.assign(active,{screen:'reflex',reflexTrial:0,reflexTotal:5,reflexTimes:[],falseStarts:0,reflexPhase:'intro'});render()}
function reflexScreen(){let p=active.reflexPhase,txt=p==='intro'?'Tap to begin':p==='wait'?'Wait…':p==='go'?'TAP':'Too soon',sub=p==='intro'?'Five trials. Wait for green, then tap as fast as possible.':p==='wait'?'Do not anticipate.':p==='go'?'React now.':`False starts: ${active.falseStarts}`,cls=p==='go'?'go':p==='bad'?'bad':'';root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.reflexTrial/active.reflexTotal*100}%"></i></div><div class="timer">${active.reflexTrial}/${active.reflexTotal}</div></div><div class="reflexWrap"><button class="reflexPad ${cls}" data-reflex><div class="bolt">⚡</div><strong>${txt}</strong><p>${sub}</p>${active.reflexTimes.length?`<div>Last: ${active.reflexTimes.at(-1)} ms</div>`:''}</button></div></main></div>`}
function reflexTap(){if(active.reflexPhase==='intro'||active.reflexPhase==='bad')return scheduleReflex();if(active.reflexPhase==='wait'){clearTimeout(active.reflexWait);active.falseStarts++;active.reflexPhase='bad';render();setTimeout(scheduleReflex,700);return}if(active.reflexPhase==='go'){active.reflexTimes.push(Date.now()-active.reflexGoAt);active.reflexTrial++;if(active.reflexTrial>=active.reflexTotal)return finishReflex();active.reflexPhase='intro';render();setTimeout(scheduleReflex,600)}}
function scheduleReflex(){if(!active||active.screen!=='reflex')return;active.reflexPhase='wait';render();active.reflexWait=setTimeout(()=>{if(active?.screen==='reflex'){active.reflexPhase='go';active.reflexGoAt=Date.now();render()}},ri(1200,3200))}
function finishReflex(){let ms=med(active.reflexTimes),acc=Math.max(0,1-active.falseStarts/(5+active.falseStarts));active.good=5;active.count=5;active.times=active.reflexTimes;finishBlock(acc,ms,{falseStarts:active.falseStarts})}
function finishBlock(forcedAcc=null,forcedMs=null,meta={}){clearTimers();let id=active.id,d=S.domains[id],acc=forcedAcc??active.good/active.count,ms=forcedMs??med(active.times),sc=score(acc,ms,d.level,id),nl=adapt(d.level,acc,ms,id),r={id,acc,ms,score:sc,level:d.level,next:nl,meta};if(!active.practice){d.score=d.attempts?Math.round(d.score*.68+sc*.32):sc;d.level=nl;d.attempts+=active.count;d.last=new Date().toISOString();d.best=Math.max(d.best,sc);saveState()}active.results.push(r);active.screen='blockResult';render()}
function blockResult(){let r=active.results.at(-1);root.innerHTML=`<div class="app"><div class="score"><div class="eye">${active.practice?'Practice':'System complete'}</div><h2 style="margin:8px 0">${META[r.id][0]}</h2><div class="n">${r.score}<span>/100</span></div></div><div class="grid2"><div class="metric"><small>Accuracy</small><strong>${Math.round(r.acc*100)}%</strong></div><div class="metric"><small>${r.id==='reflex'?'Median RT':'Median speed'}</small><strong>${r.id==='reflex'?Math.round(r.ms)+'ms':(r.ms/1000).toFixed(2)+'s'}</strong></div><div class="metric"><small>Difficulty</small><strong>${r.level}→${r.next}</strong></div><div class="metric"><small>Status</small><strong style="font-size:15px">${r.acc<.6?'Overloaded':r.acc>=.9?'Progress':'Productive'}</strong></div></div><button class="btn primary" style="width:100%;margin-top:14px" data-next>${active.practice?'Back to Games':active.bi+1>=active.ids.length?'Finish Session':'Next System'}</button></div>`}
function nextBlock(){if(active.practice){active=null;page='games';return render()}if(++active.bi>=active.ids.length)return finishSession();active.screen='question';begin()}
function finishSession(){let mins=(Date.now()-active.start)/60000,sc=Math.round(active.results.reduce((a,r)=>a+r.score,0)/active.results.length),today=dayKey();if(S.stats.last!==today){if(S.stats.last&&Math.round((new Date(today)-new Date(S.stats.last))/86400000)===1)S.stats.streak++;else S.stats.streak=1}S.stats.last=today;S.stats.sessions++;S.stats.minutes+=mins;let h={date:new Date().toISOString(),mode:active.mode,score:sc,results:active.results,minutes:mins};S.history.push(h);S.history=S.history.slice(-60);saveState();active={screen:'sessionResult',h};render()}
function sessionResult(){let h=active.h,b=[...h.results].sort((a,b)=>b.score-a.score),w=b.at(-1);root.innerHTML=`<div class="app"><div class="score"><div class="eye">Session complete</div><div class="n">${h.score}<span>/100</span></div><p>${META[w.id][0]} generated the weakest current signal.</p></div><div class="grid2"><div class="metric"><small>Strongest</small><strong style="font-size:15px">${META[b[0].id][0]}</strong></div><div class="metric"><small>Priority</small><strong style="font-size:15px">${META[w.id][0]}</strong></div><div class="metric"><small>Systems</small><strong>${h.results.length}/16</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div></div><button class="btn primary" style="width:100%;margin-top:14px" data-done>Return to Today</button></div>`}
document.addEventListener('click',e=>{let n=e.target.closest('[data-nav]');if(n){clearTimers();active=null;page=n.dataset.nav;return render()}let s=e.target.closest('[data-start]');if(s)return start(s.dataset.start);let p=e.target.closest('[data-practice]');if(p)return start('practice',p.dataset.practice);let a=e.target.closest('[data-answer]');if(a)return answer(a.dataset.answer);if(e.target.closest('[data-reflex]'))return reflexTap();let l=e.target.closest('[data-letter]');if(l&&active?.screen==='words'){active.wordUsed.push(Number(l.dataset.letter));return wordsScreen()}if(e.target.closest('[data-word-back]')&&active?.screen==='words'){active.wordUsed.pop();return wordsScreen()}if(e.target.closest('[data-word-shuffle]')&&active?.screen==='words'){active.wordLetters=sh(active.wordLetters);active.wordUsed=[];return wordsScreen()}if(e.target.closest('[data-word-submit]')&&active?.screen==='words')return wordSubmit();if(e.target.closest('[data-next]'))return nextBlock();if(e.target.closest('[data-done]')){active=null;page='today';return render()}if(e.target.closest('[data-exit]')){if(confirm('Exit this training block?')){clearTimers();active=null;page='today';render()}}});
document.addEventListener('submit',e=>{if(e.target.id==='form'){e.preventDefault();let v=document.getElementById('ans').value.trim();if(v)answer(v)}});
window.addEventListener('error',e=>{clearTimers();root.innerHTML=`<div class="err"><b>SHARP runtime error</b><br><br>${esc(e.message||'Unknown error')}</div>`});
saveState();render();
