'use strict';
const root=document.getElementById('root');let page='today',active=null,timerHandle=null,memoryHandle=null,stimulusHandle=null;
function clearTimers(){clearInterval(timerHandle);clearTimeout(memoryHandle);clearTimeout(stimulusHandle);clearTimeout(active?.reflexWait);timerHandle=memoryHandle=stimulusHandle=null}
function nav(){return`<nav class="nav">${[['today','⌂','Today'],['train','▶','Train'],['performance','⌁','Performance'],['games','◇','Games']].map(x=>`<button data-nav="${x[0]}" class="${page===x[0]?'on':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
function shell(x){return`<div class="app"><div class="top"><div class="logo">SHARP</div><div class="dot"></div></div>${x}</div>${nav()}`}
function index(){let trained=IDS.filter(id=>S.domains[id].attempts),vals=trained.map(normalizedDomain).filter(x=>x!=null),v=vals.length>=8?Math.round(avg(vals)-(IDS.length-trained.length)*.6):null;return{v,trained}}
function focus(){return [...IDS].filter(id=>id!=='reflex').sort((a,b)=>((normalizedDomain(a)??50)+days(S.domains[a].last)*-1.5)-((normalizedDomain(b)??50)+days(S.domains[b].last)*-1.5))[0]}
function drow(id){let d=S.domains[id],n=normalizedDomain(id);return`<div class="drow"><div class="dtop"><span>${META[id][0]} · L${d.level}</span><b>${d.attempts?(n??d.score):'BASELINE'}</b></div><div class="bar"><i style="width:${d.attempts?(n??d.score):0}%"></i></div></div>`}
function game(id){let d=S.domains[id];return`<div class="game" data-practice="${id}"><div class="ico">${META[id][1]}</div><div><h3>${META[id][0]}</h3><p>${META[id][2]}</p></div><div class="lvl"><small>LEVEL</small><strong>${d.level}</strong></div></div>`}
function today(){let f=focus(),ix=index();root.innerHTML=shell(`<section class="hero"><div class="eye">Daily cognitive training</div><h1>Train the full<br>system.</h1><p>Eighteen measured cognitive systems. Full Daily tests all 18, then adds one weakness block.</p></section><section class="card focus"><div class="head"><div><div class="eye">Current priority</div><h2 style="margin-top:7px">${META[f][0]}</h2></div><span class="chip">LEVEL ${S.domains[f].level}</span></div><p>${S.domains[f].attempts?'Lowest current normalized signal.':'Baseline data needed.'}</p><div class="row"><button class="btn primary" data-start="standard">Full Daily</button><button class="btn secondary" data-start="quick">Quick</button></div></section><div class="section"><h3>Current signal</h3><span>50 = personal baseline</span></div><div class="grid3"><div class="metric"><small>Sharpness</small><strong>${ix.v??'—'}</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div><div class="metric"><small>Minutes</small><strong>${Math.round(S.stats.minutes)}</strong></div></div>`)}
function train(){root.innerHTML=shell(`<section class="hero"><div class="eye">Session control</div><h1>Choose the<br>workload.</h1><p>Full Daily runs baseline probes, core cognition, executive pressure, then a weakness bonus. Quick targets six systems.</p></section><div class="grid2"><section class="card"><div class="eye">Quick</div><h2 style="margin-top:7px">10–15m</h2><p>Six targeted systems.</p><button class="btn primary" data-start="quick" style="width:100%">Start</button></section><section class="card"><div class="eye">Full Daily</div><h2 style="margin-top:7px">30–40m</h2><p>18 systems + weakness bonus.</p><button class="btn primary" data-start="standard" style="width:100%">Start</button></section></div><div class="section"><h3>Full Daily phases</h3></div><section class="card"><p><b>1. Baseline probes</b><br>Reflex · Processing · Sustained Attention · Stroop</p><p><b>2. Core cognition</b><br>Maths · Logic · Patterns · Matrix · Spatial · Memory · Language</p><p><b>3. Executive pressure</b><br>Flexibility · Dual Task · Planning · Strategy</p><p><b>4. Weakness bonus</b><br>One extra block from your lowest signal.</p></section>`)}
function performancePage(){let ix=index(),rank=[...ix.trained].sort((a,b)=>(normalizedDomain(b)??0)-(normalizedDomain(a)??0)),hist=[...S.history].reverse().slice(0,6);root.innerHTML=shell(`<section class="hero"><div class="eye">Performance intelligence</div><h1>${ix.v??'—'}<span style="font-size:.32em;color:var(--mut)"> /100</span></h1><p>${ix.v==null?'Complete more domains to establish the index.':'Personal-normalized index: 50 represents your established baseline, not population IQ.'}</p></section><div class="grid3"><div class="metric"><small>Sessions</small><strong>${S.stats.sessions}</strong></div><div class="metric"><small>Trained</small><strong>${ix.trained.length}/18</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div></div>${rank.length?`<div class="section"><h3>Signal</h3></div><div class="grid2"><div class="metric"><small>Strongest</small><strong style="font-size:15px">${META[rank[0]][0]}</strong></div><div class="metric"><small>Weakest</small><strong style="font-size:15px">${META[rank.at(-1)][0]}</strong></div></div>`:''}<div class="section"><h3>Domain profile</h3></div><section class="card">${IDS.map(drow).join('')}</section><div class="section"><h3>Recent sessions</h3></div>${hist.length?hist.map(h=>`<div class="game"><div class="ico">${h.score}</div><div><h3>${h.mode==='standard'?'Full Daily':'Quick'} session</h3><p>${new Date(h.date).toLocaleDateString()} · ${h.results.length} blocks</p></div></div>`).join(''):'<div class="empty">No completed sessions yet.</div>'}`)}
function gamesPage(){root.innerHTML=shell(`<section class="hero"><div class="eye">Practice lab</div><h1>Train one<br>system.</h1><p>Practice does not affect your daily streak.</p></section>${IDS.map(game).join('')}`)}
function render(){if(active?.screen==='question')return question();if(active?.screen==='memory')return memoryScreen();if(active?.screen==='visualmem')return visualMemoryScreen();if(active?.screen==='words')return wordsScreen();if(active?.screen==='reflex')return reflexScreen();if(active?.screen==='sustained')return sustainedScreen();if(active?.screen==='dual')return dualScreen();if(active?.screen==='blockResult')return blockResult();if(active?.screen==='sessionResult')return sessionResult();({today,train,performance:performancePage,games:gamesPage}[page]||today)()}
function quickIds(){return [...IDS].sort((a,b)=>((normalizedDomain(a)??50)+Math.random()*12)-((normalizedDomain(b)??50)+Math.random()*12)).slice(0,6)}
function fullIds(){let phase1=['reflex','processing','sustained','attention'];let phase2=['arithmetic','estimation','logic','patterns','matrix','spatial','memory','visualmem','words','verbal'];let phase3=['flexibility','dual','planning','strategy'];let weak=focus();return [...phase1,...phase2,...phase3,weak]}
function start(mode,only){let ids=only?[only]:(mode==='standard'?fullIds():quickIds());active={mode,practice:!!only,ids,bi:0,results:[],start:Date.now(),screen:'question'};begin()}
function countFor(id,mode){if(id==='reflex')return 5;if(id==='words'||id==='sustained'||id==='dual')return 1;return mode==='quick'?4:5}
function begin(){clearTimers();let id=active.ids[active.bi];Object.assign(active,{id,qi:0,count:countFor(id,active.mode),good:0,times:[],errors:[],prevRule:null,timeouts:0,deadline:null,limit:null});if(id==='words')return startWords();if(id==='reflex')return startReflex();if(id==='sustained')return startSustained();if(id==='dual')return startDual();next()}
function next(){if(active.qi>=active.count)return finishBlock();let q=gen(active.id,S.domains[active.id].level,active.prevRule);active.q=q;if(q.kind==='memory'){active.screen='memory';active.memoryHidden=false;render();memoryHandle=setTimeout(()=>{if(active?.q===q){active.memoryHidden=true;active.qStart=Date.now();render()}},q.display);return}if(q.kind==='visualmem'){active.screen='visualmem';active.memoryHidden=false;render();memoryHandle=setTimeout(()=>{if(active?.q===q){active.memoryHidden=true;active.qStart=Date.now();render()}},q.display);return}active.screen='question';active.qStart=Date.now();active.limit=timeLimit(active.id,S.domains[active.id].level);active.deadline=Date.now()+active.limit*1000;render();timerHandle=setInterval(updateTimer,100)}
function updateTimer(){if(!active||!active.deadline)return;let rem=(active.deadline-Date.now())/1000,n=document.getElementById('timerNum'),f=document.getElementById('timerFill');if(n)n.textContent=Math.max(0,rem).toFixed(1)+'s';if(f){let p=cl(rem/active.limit*100,0,100);f.style.width=p+'%';f.classList.toggle('low',p<25)}if(rem<=0){clearInterval(timerHandle);timerHandle=null;if(active.screen==='words')finishWords();else if(active.screen==='dual')dualTimeout();else timeoutQuestion()}}
function timeoutQuestion(){if(!active)return;active.times.push(active.limit*1000);active.errors.push('timeout');active.timeouts++;flash(false,active.q?.answer??'Timeout');active.qi++;setTimeout(next,400)}
function headProgress(showTimer=true){return`<div class="shead"><button class="x" data-exit>×</button><div><div class="prog"><i style="width:${((active.bi+active.qi/Math.max(1,active.count))/active.ids.length)*100}%"></i></div>${showTimer?'<div class="prog" style="margin-top:7px"><i id="timerFill" style="width:100%"></i></div>':''}</div><div class="timer" id="timerNum">${showTimer&&active.limit?active.limit.toFixed(1)+'s':''}</div></div>`}
function question(){let q=active.q;root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap"><div class="eye">${META[active.id][0]} · Level ${S.domains[active.id].level} · ${active.qi+1}/${active.count}</div>${questionVisual(q)}<div class="sub">${esc(q.sub||'')}</div></div>${answerUI(q)}</main></div>`;updateTimer();if(q.kind==='number')setTimeout(()=>document.getElementById('ans')?.focus(),30)}
function gridHtml(key,n){return`<div class="miniGrid" style="grid-template-columns:repeat(${n},1fr)">${String(key).split('').map(x=>`<i class="${x==='1'?'on':''}"></i>`).join('')}</div>`}
function questionVisual(q){if(q.kind==='matrix')return`<div class="matrix">${q.cells.map((x,i)=>`<div class="mcell ${i===8?'miss':''}">${esc(x)}</div>`).join('')}</div>`;if(q.kind==='matrixGrid')return`<div class="matrix">${q.cells.map((x,i)=>`<div class="mcell ${i===8?'miss':''}">${i===8?'?':gridHtml(x,q.n)}</div>`).join('')}</div>`;if(q.kind==='spatial')return`<div style="margin:18px auto">${gridHtml(q.baseKey,q.n)}<div class="eye" style="margin-top:12px">${esc(q.sub)}</div></div>`;if(q.kind==='route'){let walls=new Set(q.walls);return`<div class="routeGrid" style="grid-template-columns:repeat(${q.n},1fr)">${Array.from({length:q.n*q.n},(_,i)=>`<div class="routeCell ${i===0?'start':i===q.n*q.n-1?'goal':walls.has(i)?'wall':''}">${i===0?'S':i===q.n*q.n-1?'G':''}</div>`).join('')}</div>`}if(q.kind==='stroop')return`<div class="q" style="color:${q.ink};margin-top:18px">${esc(q.prompt)}</div>`;return`<div class="q ${String(q.prompt).length>42?'compact':''}" style="margin-top:16px">${esc(q.prompt)}</div>`}
function answerUI(q){if(q.kind==='matrix')return`<div class="matrixAnswers">${q.options.map(o=>`<button class="matrixOption" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(q.kind==='matrixGrid')return`<div class="patternAnswers">${q.options.map(o=>`<button class="patternOption" data-answer="${o}">${gridHtml(o,q.n)}</button>`).join('')}</div>`;if(q.kind==='spatial'||q.kind==='visualmem')return`<div class="patternAnswers">${q.options.map(o=>`<button class="patternOption" data-answer="${o}">${gridHtml(o,q.n)}</button>`).join('')}</div>`;if(q.kind==='choice'||q.kind==='route'||q.kind==='stroop')return`<div class="options">${q.options.map(o=>`<button class="option" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;return`<form class="form" id="form"><input class="input" id="ans" inputmode="numeric" autocomplete="off" placeholder="Answer"><button class="btn primary submit" type="submit">→</button></form>`}
function answer(r){if(!active)return;clearInterval(timerHandle);let ms=Math.max(1,Date.now()-active.qStart),ok=correct(active.q,r);active.times.push(ms);if(ok)active.good++;else active.errors.push(ms<850?'impulsive':'incorrect');if(active.id==='flexibility')active.prevRule=active.q.meta?.rule||active.prevRule;flash(ok,active.q.answer);active.qi++;setTimeout(next,330)}
function flash(ok,a){let d=document.createElement('div');d.className='feedback '+(ok?'ok':'no');d.textContent=ok?'Correct':'Answer: '+a;document.body.appendChild(d);setTimeout(()=>d.remove(),550)}
function memoryScreen(){let q=active.q,hidden=active.memoryHidden;root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.qi/active.count*100}%"></i></div><div class="timer">${active.qi+1}/${active.count}</div></div><div class="qwrap"><div class="eye">Working Memory · Level ${S.domains.memory.level}</div><div class="q" style="margin-top:18px">${hidden?'Enter reverse sequence':esc(q.prompt)}</div><div class="sub">${hidden?'Reverse the order from memory.':'Memorise this sequence.'}</div></div>${hidden?answerUI({kind:'number'}):''}</main></div>`;if(hidden)setTimeout(()=>document.getElementById('ans')?.focus(),30)}
function visualMemoryScreen(){let q=active.q,hidden=active.memoryHidden;root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.qi/active.count*100}%"></i></div><div class="timer">${active.qi+1}/${active.count}</div></div><div class="qwrap"><div class="eye">Visual Memory · Level ${S.domains.visualmem.level}</div>${hidden?'<h2>Which pattern did you see?</h2>':gridHtml(q.pattern,q.n)}<div class="sub">${hidden?'Select from memory.':'Memorise the highlighted cells.'}</div></div>${hidden?answerUI(q):''}</main></div>`}
function startWords(){let bank=pk(WORD_BANK),l=S.domains.words.level,total=Math.max(42,72-l*3);Object.assign(active,{screen:'words',wordBank:bank,wordLetters:sh(bank.l.split('')),wordUsed:[],wordFound:[],wordTarget:cl(Math.min(bank.w.length,4+Math.floor(l*.65)),4,10),limit:total,deadline:Date.now()+total*1000,wordLast:Date.now()});render();timerHandle=setInterval(updateTimer,100)}
function wordsScreen(){let cur=active.wordUsed.map(i=>active.wordLetters[i]).join('');root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap" style="justify-content:flex-start;padding-top:42px"><div class="eye">Word Fluency · Level ${S.domains.words.level}</div><h2 style="margin-top:8px">Anagram Sprint</h2><p>${active.wordFound.length}/${active.wordTarget} target words · 3+ letters</p><div class="wordbuild">${esc(cur)||'&nbsp;'}</div><div class="tiles">${active.wordLetters.map((c,i)=>`<button class="tile" data-letter="${i}" ${active.wordUsed.includes(i)?'disabled':''}>${c}</button>`).join('')}</div><div class="wordactions"><button class="btn secondary" data-word-back>⌫</button><button class="btn secondary" data-word-shuffle>Shuffle</button><button class="btn primary" data-word-submit>↵</button></div><div class="found">${esc(active.wordFound.join(' · '))}</div></div></main></div>`;updateTimer()}
function wordSubmit(){let w=active.wordUsed.map(i=>active.wordLetters[i]).join('').toLowerCase();active.wordUsed=[];if(w.length<3)return wordNote('3+ letters');if(active.wordFound.includes(w))return wordNote('Already found');if(active.wordBank.w.includes(w)){active.wordFound.push(w);wordNote('✓ '+w,true)}else wordNote('Not in this challenge list')}
function wordNote(t,ok=false){flash(ok,t);render();if(active.wordFound.length>=active.wordTarget)finishWords()}
function finishWords(){clearInterval(timerHandle);let acc=cl(active.wordFound.length/active.wordTarget,0,1),elapsed=Math.max(1000,Date.now()-(active.deadline-active.limit*1000));active.good=Math.round(acc*10);active.count=10;active.times=[elapsed];active.wordExtra={found:active.wordFound.length,target:active.wordTarget};finishBlock({accOverride:acc})}
function startReflex(){Object.assign(active,{screen:'reflex',reflexTrial:0,reflexTimes:[],reflexFalse:0,reflexState:'ready'});scheduleReflex()}
function scheduleReflex(){if(active.reflexTrial>=5)return finishReflex();active.reflexState='wait';render();active.reflexWait=setTimeout(()=>{if(!active||active.screen!=='reflex')return;active.reflexState='go';active.reflexGo=Date.now();render()},ri(900,2400))}
function reflexScreen(){let go=active.reflexState==='go',bad=active.reflexState==='bad';root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${active.reflexTrial/5*100}%"></i></div><div class="timer">${active.reflexTrial+1}/5</div></div><div class="reflexWrap"><button class="reflexPad ${go?'go':bad?'bad':''}" data-reflex><div class="bolt">${go?'⚡':bad?'×':'•'}</div><h2>${go?'TAP NOW':bad?'TOO EARLY':'WAIT'}</h2><p>${go?'React as fast as possible.':bad?'Trial repeats.':'Do not anticipate.'}</p></button></div></main></div>`}
function reflexTap(){if(active.reflexState==='wait'){clearTimeout(active.reflexWait);active.reflexFalse++;active.reflexState='bad';render();setTimeout(scheduleReflex,650);return}if(active.reflexState==='go'){let rt=Date.now()-active.reflexGo;active.reflexTimes.push(rt);active.reflexTrial++;active.reflexState='ready';setTimeout(scheduleReflex,400)}}
function finishReflex(){let ms=med(active.reflexTimes),acc=cl(1-active.reflexFalse/(active.reflexFalse+5),0,1);active.good=Math.round(acc*10);active.count=10;active.times=[ms];finishBlock({accOverride:acc,msOverride:ms})}
function startSustained(){let l=S.domains.sustained.level,total=cl(26+l*2,28,46),interval=cl(760-l*35,420,760);Object.assign(active,{screen:'sustained',susTotal:total,susIndex:0,susInterval:interval,susHits:0,susMiss:0,susFalse:0,susCorrectNoGo:0,susRT:[],susFirstRT:[],susSecondRT:[],susStim:null,susTapped:false,susStarted:Date.now(),susRule:l>=7?'Tap BLUE shapes. Ignore every other colour.':'Tap every shape EXCEPT red.'});nextStimulus()}
function makeStim(){let colors=[['red','#ff6666'],['blue','#6aa9ff'],['green','#75d67a'],['yellow','#ffd85c']],shapes=['●','▲','■'];let c=pk(colors),shape=pk(shapes),l=S.domains.sustained.level,go=l>=7?c[0]==='blue':c[0]!=='red';return{colorName:c[0],color:c[1],shape,go}}
function nextStimulus(){clearTimeout(stimulusHandle);if(active.susStim){if(active.susStim.go&&!active.susTapped)active.susMiss++;if(!active.susStim.go&&!active.susTapped)active.susCorrectNoGo++}if(active.susIndex>=active.susTotal)return finishSustained();active.susStim=makeStim();active.susTapped=false;active.susShown=Date.now();active.susIndex++;render();stimulusHandle=setTimeout(nextStimulus,active.susInterval)}
function sustainedTap(){if(!active?.susStim||active.susTapped)return;active.susTapped=true;let rt=Date.now()-active.susShown;if(active.susStim.go){active.susHits++;active.susRT.push(rt);(active.susIndex<=active.susTotal/2?active.susFirstRT:active.susSecondRT).push(rt)}else active.susFalse++;render()}
function sustainedScreen(){let s=active.susStim,p=Math.round(active.susIndex/active.susTotal*100);root.innerHTML=`<div class="app"><main class="session"><div class="shead"><button class="x" data-exit>×</button><div class="prog"><i style="width:${p}%"></i></div><div class="timer">${active.susIndex}/${active.susTotal}</div></div><div class="qwrap"><div class="eye">Sustained Attention · Level ${S.domains.sustained.level}</div><h2 style="margin:10px 0 0">${esc(active.susRule)}</h2><button data-sustained style="margin:38px auto 0;width:min(330px,82vw);height:min(330px,42vh);border-radius:28px;border:1px solid var(--line);background:var(--p);color:${s?.color||'var(--txt)'};font-size:90px;font-weight:900">${s?.shape||''}</button><p>Hits ${active.susHits} · Misses ${active.susMiss} · False taps ${active.susFalse}</p></div></main></div>`}
function finishSustained(){clearTimeout(stimulusHandle);let goTotal=active.susHits+active.susMiss,noGoTotal=active.susFalse+active.susCorrectNoGo,hitRate=goTotal?active.susHits/goTotal:0,commissionRate=noGoTotal?active.susFalse/noGoTotal:0,first=med(active.susFirstRT),second=med(active.susSecondRT),drift=first&&second?Math.max(0,second-first):0,acc=cl(hitRate*(1-commissionRate),0,1),ms=med(active.susRT)||active.susInterval;active.good=Math.round(acc*100);active.count=100;active.times=[ms];finishBlock({accOverride:acc,msOverride:ms,extra:{hitRate,commissionRate,drift}})}
function startDual(){let l=S.domains.dual.level,cycles=active.mode==='quick'?1:2;Object.assign(active,{screen:'dual',dualCycle:0,dualCycles:cycles,dualMathGood:0,dualMathTotal:0,dualRecallGood:0,dualRecallTotal:0,dualTimes:[]});beginDualCycle()}
function beginDualCycle(){if(active.dualCycle>=active.dualCycles)return finishDual();let l=S.domains.dual.level,len=cl(3+Math.floor(l/3),3,6),seq=Array.from({length:len},()=>ri(1,9));active.dualSeq=seq;active.dualStage='show';active.dualMathLeft=cl(2+Math.floor(l/3),2,5);active.dualCurrent=null;render();memoryHandle=setTimeout(()=>{if(active?.screen==='dual'){active.dualStage='math';nextDualMath()}},cl(2600-l*100,1500,2600))}
function nextDualMath(){if(active.dualMathLeft<=0){active.dualStage='recall';active.limit=timeLimit('dual',S.domains.dual.level);active.deadline=Date.now()+active.limit*1000;active.qStart=Date.now();render();timerHandle=setInterval(updateTimer,100);return}let a=ri(6,25),b=ri(3,18),op=Math.random()<.5?'+':'−',ans=op==='+'?a+b:a-b;active.dualCurrent={prompt:`${a} ${op} ${b}`,answer:ans};active.limit=cl(8-S.domains.dual.level*.35,4.5,8);active.deadline=Date.now()+active.limit*1000;active.qStart=Date.now();render();timerHandle=setInterval(updateTimer,100)}
function dualScreen(){let stage=active.dualStage;if(stage==='show')root.innerHTML=`<div class="app"><main class="session">${headProgress(false)}<div class="qwrap"><div class="eye">Dual Task · Level ${S.domains.dual.level}</div><h2>Memorise and hold</h2><div class="q" style="margin-top:20px">${active.dualSeq.join('   ')}</div><p>Do not write it down. You will recall it backwards after interference.</p></div></main></div>`;else if(stage==='math')root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap"><div class="eye">Dual Task · Hold the sequence</div><div class="q">${esc(active.dualCurrent.prompt)}</div><p>Solve this while keeping the original sequence in memory.</p></div><form class="form" id="dualForm"><input class="input" id="dualAns" inputmode="numeric" autocomplete="off" placeholder="Answer"><button class="btn primary submit" type="submit">→</button></form></main></div>`;else root.innerHTML=`<div class="app"><main class="session">${headProgress()}<div class="qwrap"><div class="eye">Dual Task · Recall</div><h2>Enter the original sequence backwards</h2><p>Arithmetic interference is finished.</p></div><form class="form" id="dualRecallForm"><input class="input" id="dualRecall" inputmode="numeric" autocomplete="off" placeholder="Reverse sequence"><button class="btn primary submit" type="submit">→</button></form></main></div>`;updateTimer();setTimeout(()=>document.getElementById(stage==='math'?'dualAns':'dualRecall')?.focus(),30)}
function dualMathAnswer(v){clearInterval(timerHandle);let ok=Number(v)===active.dualCurrent.answer,ms=Date.now()-active.qStart;active.dualMathTotal++;if(ok)active.dualMathGood++;active.dualTimes.push(ms);flash(ok,active.dualCurrent.answer);active.dualMathLeft--;setTimeout(nextDualMath,260)}
function dualRecallAnswer(v){clearInterval(timerHandle);let ans=[...active.dualSeq].reverse().join(''),ok=String(v).replace(/\D/g,'')===ans,ms=Date.now()-active.qStart;active.dualRecallTotal++;if(ok)active.dualRecallGood++;active.dualTimes.push(ms);flash(ok,ans);active.dualCycle++;setTimeout(beginDualCycle,330)}
function dualTimeout(){if(active.dualStage==='math'){active.dualMathTotal++;active.dualTimes.push(active.limit*1000);active.dualMathLeft--;flash(false,active.dualCurrent.answer);setTimeout(nextDualMath,260)}else if(active.dualStage==='recall'){active.dualRecallTotal++;active.dualTimes.push(active.limit*1000);active.dualCycle++;flash(false,[...active.dualSeq].reverse().join(''));setTimeout(beginDualCycle,330)}}
function finishDual(){let math=active.dualMathTotal?active.dualMathGood/active.dualMathTotal:0,recall=active.dualRecallTotal?active.dualRecallGood/active.dualRecallTotal:0,acc=(math+recall)/2,ms=med(active.dualTimes);active.good=Math.round(acc*100);active.count=100;active.times=[ms];finishBlock({accOverride:acc,msOverride:ms,extra:{math,recall}})}
function finishBlock(o={}){clearTimers();let id=active.id,d=S.domains[id],acc=o.accOverride??(active.count?active.good/active.count:0),ms=o.msOverride??med(active.times),sc=score(acc,ms,d.level,id,o.extra||{}),res={id,acc,ms,score:sc,level:d.level,next:d.level,extra:o.extra||{}};if(!active.practice){if(d.baseline==null)d.baseline=sc;d.score=d.attempts?Math.round(d.score*.72+sc*.28):sc;let recentResult={acc,ms,level:d.level,score:sc};let nl=stableAdapt(id,d,recentResult);d.recent=[...(d.recent||[]),recentResult].slice(-6);d.level=nl;d.attempts+=(id==='sustained'||id==='dual'||id==='words'||id==='reflex')?1:active.count;d.last=new Date().toISOString();d.best=Math.max(d.best,sc);res.next=nl;saveState()}active.results.push(res);active.screen='blockResult';render()}
function blockResult(){let r=active.results.at(-1),trend=normalizedDomain(r.id);root.innerHTML=`<div class="app"><div class="score"><div class="eye">${active.practice?'Practice':'Block complete'}</div><h2 style="margin:8px 0">${META[r.id][0]}</h2><div class="n">${r.score}<span>/100</span></div></div><div class="grid2"><div class="metric"><small>Accuracy</small><strong>${Math.round(r.acc*100)}%</strong></div><div class="metric"><small>Median speed</small><strong>${r.ms?((r.ms/1000).toFixed(2)+'s'):'—'}</strong></div><div class="metric"><small>Level</small><strong>${r.level}→${r.next}</strong></div><div class="metric"><small>Normalized</small><strong>${trend??'—'}</strong></div></div><p style="text-align:center">${r.next>r.level?'Promotion earned from multi-block consistency.':r.next<r.level?'Difficulty reduced after repeated low accuracy.':'Level held until the recent performance window justifies a move.'}</p><button class="btn primary" style="width:100%;margin-top:14px" data-next>${active.practice?'Back to Games':active.bi+1>=active.ids.length?'Finish Session':'Next Block'}</button></div>`}
function nextBlock(){if(active.practice){active=null;page='games';return render()}if(++active.bi>=active.ids.length)return finishSession();active.screen='question';begin()}
function finishSession(){let mins=(Date.now()-active.start)/60000,sc=Math.round(avg(active.results.map(r=>r.score))),today=dayKey();if(S.stats.last!==today){let gap=S.stats.last?Math.round((new Date(today)-new Date(S.stats.last))/86400000):99;S.stats.streak=gap===1?S.stats.streak+1:1}S.stats.last=today;S.stats.sessions++;S.stats.minutes+=mins;let h={date:new Date().toISOString(),mode:active.mode,score:sc,results:active.results,minutes:mins};S.history.push(h);S.history=S.history.slice(-60);saveState();active={screen:'sessionResult',h};render()}
function sessionResult(){let h=active.h,b=[...h.results].sort((a,b)=>b.score-a.score),w=b.at(-1);root.innerHTML=`<div class="app"><div class="score"><div class="eye">Session complete</div><h2 style="margin:8px 0">${h.mode==='standard'?'Full Daily':'Quick'} training</h2><div class="n">${h.score}<span>/100</span></div><p>${META[w.id][0]} was the lowest block today. Full Daily will continue probing all systems while the bonus block prioritises weakness.</p></div><div class="grid2"><div class="metric"><small>Strongest</small><strong style="font-size:15px">${META[b[0].id][0]}</strong></div><div class="metric"><small>Constraint</small><strong style="font-size:15px">${META[w.id][0]}</strong></div><div class="metric"><small>Blocks</small><strong>${h.results.length}</strong></div><div class="metric"><small>Streak</small><strong>${S.stats.streak}d</strong></div></div><button class="btn primary" style="width:100%;margin-top:14px" data-done>Return to Today</button></div>`}
document.addEventListener('click',e=>{let n=e.target.closest('[data-nav]');if(n){clearTimers();active=null;page=n.dataset.nav;return render()}let s=e.target.closest('[data-start]');if(s)return start(s.dataset.start);let p=e.target.closest('[data-practice]');if(p)return start('practice',p.dataset.practice);let a=e.target.closest('[data-answer]');if(a)return answer(a.dataset.answer);let l=e.target.closest('[data-letter]');if(l){active.wordUsed.push(Number(l.dataset.letter));return render()}if(e.target.closest('[data-word-back]')){active.wordUsed.pop();return render()}if(e.target.closest('[data-word-shuffle]')){active.wordLetters=sh(active.wordLetters);active.wordUsed=[];return render()}if(e.target.closest('[data-word-submit]'))return wordSubmit();if(e.target.closest('[data-reflex]'))return reflexTap();if(e.target.closest('[data-sustained]'))return sustainedTap();if(e.target.closest('[data-next]'))return nextBlock();if(e.target.closest('[data-done]')){active=null;page='today';return render()}if(e.target.closest('[data-exit]')){if(confirm('Exit this block?')){clearTimers();active=null;page='today';render()}}});
document.addEventListener('submit',e=>{if(e.target.id==='form'){e.preventDefault();let v=document.getElementById('ans').value.trim();if(v)answer(v)}if(e.target.id==='dualForm'){e.preventDefault();let v=document.getElementById('dualAns').value.trim();if(v)dualMathAnswer(v)}if(e.target.id==='dualRecallForm'){e.preventDefault();let v=document.getElementById('dualRecall').value.trim();if(v)dualRecallAnswer(v)}});
window.addEventListener('error',e=>{clearTimers();root.innerHTML=`<div class="err"><b>SHARP runtime error</b><br><br>${esc(e.message||'Unknown error')}</div>`});
render();